### ISSUE TITLE
STL Files

### ISSUE THREAD

**Issue by ddworken** [grablab/openhand-hardware#2]
In the README.md it says that stl files are available but I do not see them anywhere in the folder for Common Parts. If you still have them available I would really appreciate it if could you upload them.

**Comment by grablab** [comment]
@ddworken , we never generated stl or step files for the common parts, since no one had ever expressed a need for them. The stl files for the fasteners can be found directly from the McMaster site if you look up the part number. I believe the stl's for the servo's can be found online off of vendor sites as well. You could also upload the .sldprt to Onshape and re-export as stl/step from there. If you're having trouble w/ those options, send me an email (from the project website) directly, and I'll get you the stl's you need.
